### ISSUE TITLE
Differences between `jaystack/odata-v4-parser`?

### ISSUE THREAD

**Issue by blitzmann** [Soontao/odata-v4-parser#230]
Hey there!

I'm working on updates to https://github.com/andryuha49/odata-v4-typeorm. Unfortunately, the project seems unmaintained for the most part, so I might be releasing my own packages. I noticed it's using `jaystack/odata-v4-sql` which in turn is using `jaystack/odata-v4-parser`.

All these projects seem unmaintained, or at the very least slow. I noticed this project has had quite a bit of activity recently, and am curious about what updates / improvements it has. Also, is it more or less stable?

Having this information in the README would be very helpful as well :)

**Comment by Soontao** [comment]
hi @blitzmann 

sorry my late reply, this repo enhanced some parsing logic to avoid `undefined` issue, and provide a `builder` api to build the odata uri query. 

Thanks
