### ISSUE TITLE
geography[BUG]

### ISSUE THREAD

**Issue by Mario-35** [Soontao/odata-v4-parser#272]
Hi and thanks for this library 

?$filter=geo.distance(location,geography'POINT(-1.702 48.113)') le 200

it case a bug.

**Comment by Soontao** [comment]
sure, let me have a look

**Comment by Soontao** [comment]
Hi @Mario-35, 

Thanks your report, and your ID is really cute haha :) 

![image](https://user-images.githubusercontent.com/10473459/201878780-401e7de6-218e-43b2-86b4-f2865cbfaa66.png)

in odata official APNF standard, the `Point` literal should have `SRID` literal as prefix, and the `Point` literal is not uppercase, but there are many variants in `odata.org` documents, so its confused. 

I released a new version `0.2.12`, its supported uppercase `POINT` literal and geography literal without `SRID`, but carefully use them on your risk, maybe its not compatible with other implementations

**Comment by Mario-35** [comment]
Thanks I go to test and report it.

It's my real name  :)

**Comment by Mario-35** [comment]
Ok, it works I searched but don't saw it was an uppercase problem :) I use your library for sensorThings Odata and you're right, it's confused BUT in fact, I think it's POSTGRES (POSGIS)  which have some problems with lowercase and uppercase name, so to  avoid these library problems transform all in uppercase. 

sorry for my approximative english.

Thanks
