### ISSUE TITLE
[BUG] Strings with double quotescannot be parsed

### ISSUE THREAD

**Issue by higleyc** [Soontao/odata-v4-parser#274]
## Describe the bug

If double quotes are included in string literals, parsing throws an error.

## System Environment

* OS: Linux
* Node Version: 16.14.0
* This Library Version: 0.2.12

## To Reproduce
```
test('testStringEscapes', () => {
    let builder = ODataParam.New()
    let odfilter = ODataFilter.New()
    odfilter = odfilter.field("key").eq('val"')
    builder.filter(odfilter)
    let queryStr = builder.toString()
    console.log("queryStr:", queryStr)

    let ast = defaultParser.query(queryStr)
})
```

Output:
```
  console.log
    queryStr: $filter=key eq 'val"'

      at Object.log (__tests__/modules/structured_queries_test.ts:90:13)

 FAIL  __tests__/modules/structured_queries_test.ts
  ✕ testStringEscapes (28 ms)

  ● testStringEscapes

    Unexpected character at 11

      90 |     console.log("queryStr:", queryStr)
      91 |
    > 92 |     let ast = defaultParser.query(queryStr)
         |                             ^
      93 | })
      94 |

      at node_modules/@odata/parser/src/parser.ts:23:13
      at Parser.query (node_modules/@odata/parser/src/parser.ts:46:45)
      at Object.query (__tests__/modules/structured_queries_test.ts:92:29)
```

## Expected behavior
Strings with double quotes should parse without error. To my understanding the encoding is correct i.e. the double quotes should be unescaped (looking at the [ABNF](https://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/abnf/odata-abnf-construction-rules.txt))

## Additional context
None

**Comment by Soontao** [comment]
cool  will have a look today

**Comment by Soontao** [comment]
Dear @higleyc 

yep this is an issue and in fact it contains more issues, some other special characters also will cause same issue, cannot be determined as primitive value string. 

fix already ready and delivered with @odata/parser@0.2.14, please have a try. 

BR,
Theo

**Comment by higleyc** [comment]
Wow thank you for the quick fix @Soontao! That did it.
